# Site settings
title: Manuel Bautista Paredes
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Manuel Bautista Paredes
user_description: Hi! I am a Data Engineer from Spain. Since I discovered Data Science, programming has become my true passion. My main interest is distributed data processing and ETL for Machine Learning applications. In the near future I want to create online content for sharing my passion for Data Science, improving my communication skills and showing off 😎. In my free time, I enjoy practising Muay Thai and learning about economy and liberalism.
user_title: Data Engineer
email: manubp97@gmail.com
# twitter_username: lorem_ipsum
github_username: manubp97
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
