# Site settings
title: Manuel Bautista Paredes
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Manuel Bautista Paredes
user_description: I am a Data Engineer from Spain, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Data Engineer
email: manubp97@gmail.com
# twitter_username: lorem_ipsum
github_username: manubp97
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
